name: Build FFmpeg for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Create artifact
      run: cmd /c FinderBot.exe pa_19446_complete.csv

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cache
        path: /Cache
    
