name: Build FFmpeg for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-binaries
        path: /usr/local/ffmpeg
    
